# **<span style="color: #87CEEB;">Welcome to CS437/CS5317/EE414/EE513 Deep Learning</span>**

# <span style="color: #9370DB;">**Submission Guidelines**</span>

- <span style="color: #9370DB;">Please rename the file to `PA0_1_<RollNumber>`.</span>
- <span style="color: #9370DB;">Please also submit a **.py** file of every Notebook. You can do this by exporting your **ipynb** to a Python script.</span>
- <span style="color: #9370DB;">Please submit a zipped folder of both your Jupyter Notebooks and Python script files.</span>




<h1><b> Programming Assignment 0: Introduction to Python </b></h1>

Credits: This notebook is based on a [Python tutorial](http://cs231n.github.io/python-numpy-tutorial/) by [Justin Johnson](https://web.eecs.umich.edu/~justincj/) for [CS231n](http://cs231n.github.io/). 

#### Name:
#### Roll Number: 

<h1> Python </h1>

We will use the Python programming language for all assignments in this course. Python is a great general-purpose programming language on its own, but with the help of a few popular libraries it becomes a powerful environment for scientific computing.

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

### Basic data types

Like most languages, Python has a number of basic types including integers, floats, booleans, and strings. These data types behave in ways that are familiar from other programming languages.

Numbers: Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # Addition; prints "4"
print(x - 1)   # Subtraction; prints "2"
print(x * 2)   # Multiplication; prints "6"
print(x ** 2)  # Exponentiation; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

### Booleans
Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc.):

In [ ]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # Logical AND; prints "False"
print(t or f)  # Logical OR; prints "True"
print(not t)   # Logical NOT; prints "False"
print(t != f)  # Logical XOR; prints "True"

In [ ]:
grade = "A"
if grade == "A":
    print("Excellent")
elif grade == "B":
    print("Good")
elif grade == "C":
    print("OK")
else:
    print("Fail")

### Strings

In [ ]:
hello = 'hello'    # String literals can use single quotes
world = "world"    # or double quotes; it does not matter.
print(hello)       # Prints "hello"
print(len(hello))  # String length; prints "5"
hw = hello + ' ' + world  # String concatenation
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print(hw12)  # prints "hello world 12"

String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

You can find a list of all string methods in the [documentation](https://docs.python.org/3.5/library/stdtypes.html#string-methods).

### Containers
Python includes several built-in container types: lists, dictionaries, sets, and tuples.

### Lists
A list is the Python equivalent of an array, but is resizeable and can contain elements of different types

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.5/tutorial/datastructures.html#more-on-lists).

### Slicing
In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing

In [ ]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

### Loops
You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", each on its own line.

If you want access to the index of each element within the body of a loop, use the built-in enumerate function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line


### List Comprehension
When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

### Dictionaries

A dictionary stores (key, value) pairs. You can use it like this:

In [ ]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True" 
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/3.5/library/stdtypes.html#dict).

Loops: It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

If you want access to keys and their corresponding values, use the items method:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

### Sets
A set is an unordered collection of distinct elements. As a simple example, consider the following:


In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"


As usual, everything you want to know about sets can be found in the [documentation](https://docs.python.org/3.5/library/stdtypes.html#set)

### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

### Functions

Python functions are defined using the def keyword. For example:


In [2]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))
# Prints "negative", "zero", "positive"

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

There is a lot more information about Python functions in the [documentation](https://docs.python.org/3.5/tutorial/controlflow.html#defining-functions).

### Classes
The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"


You can read a lot more about Python classes in the [documentation](https://docs.python.org/3.5/tutorial/classes.html).

Finally, to wrap python basics, it is almost mandatory for all Python users to go over the 19 aphorisms that Tim Peters wrote, hiding the last one (for reasons unknown). Execute the following code:

In [ ]:
import this

# Numpy

### The soul of every single data related field of Computer Science

Numpy is the core library for scientific computing in Python. Essentially, all advanced AI requires heavy matrix manipulations, and as these manipulations are done through arrays, Numpy helps with the performance *immensely* 

If you haven't installed Numpy yet, try either of these two lines of code in your terminal:
* pip install numpy
* pip3 install numpy (MacOs)

Restart your editor, and you should be good to go

To start using Numpy, the golden line is given below:

In [ ]:
import numpy as np

### Numpy Arrays

These are just a grid of values, same type, indexed by a tuple of non-negative integers

We define the number of dimensions are the *rank* and the size of array along each of the dimension as the *shape*

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

We can create Numpy arrays in many ways, some given below:

In [ ]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Could print anything. Suprise yourself

#### Array Indexing

Numpy offers several ways to index into arrays.


In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [ ]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])


#### Datatypes

A subtle introduction to Numpy datatypes is given below. Maintaining knowledge of how datatypes work in Numpy is important to understand what you're working with, and how we you can force changes (as necessary)

In [ ]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype) 

#### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

One of the more useful functions for performing computations on arrays is the *sum* function:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

#### Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

Numpy broadcasting allows us to express the power of manipulation stated above. Consider this broadcasting:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Here are some general applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

# Matplotlib

[Matplotlib](https://matplotlib.org/) is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

### Plotting

The most important function in matplotlib is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)
plt.show()  # You must call plt.show() to make graphics appear.

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

You can read much more about the plot function in the [documentation](https://matplotlib.org/2.0.2/api/pyplot_api.html).

### Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

### Plotting Image

In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

img = cv2.imread('./sample_img.png',0) # load grayscale image(0,255). Shape (475,475)

plt.imshow(img)
plt.show()

You can read much more about the subplot function in the [documentation](https://matplotlib.org/2.0.2/api/pyplot_api.html).

<br>
<h1> <center><b>Questions Section</b></center> </h1>
<br>

# **Python Basic Questions**
Use of any external libraries is not allowed in python basic questions section until explicitly mentioned or imported in skeleton code.

#### Q 1) 
#### If the length of the list is greater than 5: Print all elements at even indices whose values are greater than the mean of the list.

#### If the length of the list is 5 or less: Print all elements at odd indices whose values are less than the mean of the list. [Python List]

In [ ]:
def process_list(lst):
    # code here
    return

print("Test Case 1:")
process_list([10, 5, 20, 15, 30, 25, 40])
print("Expected output: [30,40]")

print("\nTest Case 2:")
process_list([1, 3, 5, 7])
print("Expected output: [3]")

#### Q 2) Create a program that takes in a list of integers and removes all duplicate elements from the list. Then, sort the list in ascending order and print the final list. Do not use any built-in Python functions or libraries for removing duplicates or sorting the list. [Python List]

In [ ]:
def process_list(lst):
    # code here
    return

print("Test Case 1:")
process_list([10, 5, 20, 15, 30, 25, 40, 5, 20])
print("Expected output: [5, 10, 15, 20, 25, 30, 40]")

print("\nTest Case 2:")
process_list([1, 3, 5, 7, 3, 1])
print("Expected output: [1, 3, 5, 7]")

print("\nTest Case 3:")
process_list([100, 50, 100, 25, 50, 10])
print("Expected output: [10, 25, 50, 100]")

print("\nTest Case 4:")
process_list([])
print("Expected output: []")

print("\nTest Case 5:")
process_list([2, 2, 2, 2])
print("Expected output: [2]")

#### Q 3) Write a function that finds derivative of activation (a) wrt to weight (w) and bias (b) for a given input (x) and activation (a) using the formulae given below. The function should return the derivative of cost wrt to weight and bias. The function should work for any number of training examples. [Python Math]

$$
    a = \frac{1}{1+e^-z}
$$
<br>

$$
    z = w.x + b
$$
<br>

$$
 x,a \in R
$$

In [ ]:
import math

def derivative(x, a):
    # code here
    return dw, db

# Test Case 1: Simple input and output
x = [0.5, 1.5, 2.0]
a = [0.6, 0.8, 0.9]

print("Test Case 1:")
dw, db = derivative(x, a)
print("Expected dw: 0.180")
print("dw:", dw)
print("Expected db: ", 0.163)
print("db:", db)

# Test Case 2: All inputs are zero
x = [0, 0, 0]
a = [0.5, 0.5, 0.5]

print("\nTest Case 2:")
dw, db = derivative(x, a)
dw, db = derivative(x, a)
print("Expected dw: ", 0.0)
print("dw:", dw)
print("Expected db: ", 0.25)
print("db:", db)

# Test Case 3: Single training example
x = [1.0]
a = [0.7]

print("\nTest Case 3:")
dw, db = derivative(x, a)
dw, db = derivative(x, a)
print("Expected dw: 0.210")
print("dw:", dw)
print("Expected db: 0.210")
print("db:", db)

#### Q 4) Write a code that finds a subsequence in a given string. if the subsequence is found, the function should return the index of the first character of the subsequence in the string. If the subsequence is not found, the function should return -1. The function should work for any string and subsequence. [Python String]
#### example:

    string = "Hello World"
    subsequence = "xyz"
    output = -1

    string = "Maze Runner"
    subsequence = "zer"
    output = 2

In [ ]:
def match(subsequence, str):
    # code here
    pass

# Test Case 1: Subsequence not found
string = "Hello World"
subsequence = "xyz"
print("Test Case 1:")
print("Output:", match(subsequence, string))
print("Expected Output: -1")

# Test Case 2: Subsequence found
string = "Maze Runner"
subsequence = "zer"
print("\nTest Case 2:")
print("Output:", match(subsequence, string))
print("Expected Output: 2")

# Test Case 3: Subsequence is empty
string = "Hello World"
subsequence = ""
print("\nTest Case 3:")
print("Output:", match(subsequence, string))
print("Expected Output: 0")

# Test Case 4: String is empty
string = ""
subsequence = "abc"
print("\nTest Case 4:")
print("Output:", match(subsequence, string))
print("Expected Output: -1")

# Test Case 5: Both string and subsequence are empty
string = ""
subsequence = ""
print("\nTest Case 5:")
print("Output:", match(subsequence, string))
print("Expected Output: 0")

#### Q 5) Write a function that takes a string as input and returns a dictionary with the count of each character in the string. The function should work for any string. [Python Dictionary]

In [ ]:
def character_count(str):
    # code here
    return

# Test Case 1: String with multiple occurrences of characters
string = "apple"
print("Test Case 1:")
print("Output:", character_count(string))
print("Expected Output: {'a': 1, 'p': 2, 'l': 1, 'e': 1}")

# Test Case 2: String with all unique characters
string = "hello"
print("\nTest Case 2:")
print("Output:", character_count(string))
print("Expected Output: {'h': 1, 'e': 1, 'l': 2, 'o': 1}")

# Test Case 3: Empty string
string = ""
print("\nTest Case 3:")
print("Output:", character_count(string))
print("Expected Output: {}")


#### Q6) Use the data given below to create a class team which has the following attributes and methods:

a) Attributes: name, league, nation, players(list of class players)

b) Methods: add_player, get_player

c) constructor should take name, league, nation as input and initialize the attributes.
<br><br><br>
Now create a class player which has the following attributes and methods:
<br><br><br>
a) Attributes: name, age, goals

b) Methods: get_age, get_name

c) Constructor should take name, age, goals as input and initialize the attributes.
<br><br><br>
Finally create a dictionary of teams where key is a random number and value is an object of class team. Also add the players to the team (in players list) using the add_player method. [Python Class]
<br><br><br>
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-2b7s{text-align:right;vertical-align:bottom}
.tg .tg-za14{border-color:inherit;text-align:left;vertical-align:bottom}
.tg .tg-7zrl{text-align:left;vertical-align:bottom}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-7zrl">Leagues</th>
    <th class="tg-7zrl">Nations</th>
    <th class="tg-7zrl">Teams</th>
    <th class="tg-7zrl"> Players</th>
    <th class="tg-7zrl">Goals</th>
    <th class="tg-7zrl">Age</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-7zrl">Premier League</td>
    <td class="tg-7zrl">England</td>
    <td class="tg-7zrl">Liverpool</td>
    <td class="tg-7zrl">Salah</td>
    <td class="tg-2b7s">22</td>
    <td class="tg-2b7s">27</td>
  </tr>
  <tr>
    <td class="tg-7zrl">La Liga</td>
    <td class="tg-7zrl">Spain</td>
    <td class="tg-7zrl">Barcelona</td>
    <td class="tg-7zrl">Messi</td>
    <td class="tg-2b7s">36</td>
    <td class="tg-2b7s">32</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Serie A</td>
    <td class="tg-7zrl">Italy </td>
    <td class="tg-7zrl">Juventus</td>
    <td class="tg-7zrl">Ronaldo</td>
    <td class="tg-2b7s">50</td>
    <td class="tg-2b7s">34</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Bundesliga</td>
    <td class="tg-7zrl">Germany</td>
    <td class="tg-7zrl">Bayern Munich</td>
    <td class="tg-7zrl">Lewandowski</td>
    <td class="tg-2b7s">34</td>
    <td class="tg-2b7s">31</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Ligue 1</td>
    <td class="tg-7zrl">France</td>
    <td class="tg-7zrl">Paris Saint-German</td>
    <td class="tg-7zrl">Mbappe</td>
    <td class="tg-2b7s">18</td>
    <td class="tg-2b7s">20</td>
  </tr>
</tbody>
</table>

In [ ]:
import random
leagues_data = ['Premier League', 'La Liga', 'Serie A', 'Bundesliga', 'Ligue 1']
nation_data = ['England', 'Spain', 'Italy', 'Germany', 'France']
teams_data = ['Liverpool', 'Barcelona', 'Juventus', 'Bayern Munich', 'Paris Saint-Germain']
players_data = ['Mohamed Salah', 'Lionel Messi', 'Cristiano Ronaldo', 'Robert Lewandowski', 'Kylian Mbappe']
goals_data = [22, 36, 50, 34, 18]
age_data = [27, 32, 34, 31, 20]

# create a class team
class team:
    #write your code here
    pass
  

# create a class player
class player:
    # write your code here
    pass

#create a dictionary of teams
teams = {}

#### Q7) Write a function that takes in a list of numbers and a target number and returns the two numbers (as a list) from the list that add up to the target number. The function should work for any list of numbers and any target number.[Python List]

In [ ]:
def target_sum(lst, target):
    # your code here
    pass

# Test Case 1: Target sum exists
lst = [2, 7, 11, 15]
target = 9
print("Test Case 1:")
print("Output:", target_sum(lst, target))
print("Expected Output: [2, 7]")  # 2 + 7 = 9

# Test Case 2: Target sum does not exist
lst = [1, 4, 6, 8]
target = 11
print("\nTest Case 2:")
print("Output:", target_sum(lst, target))
print("Expected Output: None")  # No pair adds up to 11

# Test Case 3: Negative numbers involved
lst = [-1, 2, 3, 5, 8]
target = 7
print("\nTest Case 3:")
print("Output:", target_sum(lst, target))
print("Expected Output: [-1, 8]")  # -1 + 8 = 7

# Numpy Questions

#### Q8) Write a function that takes 2 parameters, an upper and lower limit, creates a 2-D array of 8 elements in total, and then alters it into a 1-D array.

In [ ]:
import numpy as np

def create(lower_limit, upper_limit):
    return

# Test Case
print("Test Case 1:")
print(create(1, 15))
print("Expected Output: [1, 3, 5, 7, 9, 11, 13, 15]")

#### Q9) Write a function which takes that numpy array as input and returns the following
 

1.   The index of the maximum value in the array
2.   Maximum value in the array
3.   Mean value of the array
4.   Standard Deviation of the array

In [ ]:
def analyze_array(arr):
    # code here
    return

print("Test Case 1:")
arr1 = np.array([1, 3, 7, 9, 2, 5])
print(analyze_array(arr1))
# Expected Output: (3, 9, 4.5, 2.813657)

print("\nTest Case 2:")
arr2 = np.array([4, 4, 4, 4])
print(analyze_array(arr2))
# Expected Output: (0, 4, 4.0, 0.0)

print("\nTest Case 3:")
arr3 = np.array([-2, -5, 1, 0, -3])
print(analyze_array(arr3))
# Expected Output: (2, 1, -1.8, 2.1354)

#### Q10) Find the indices of the numpy array that are equal to 0

In [ ]:
def find_zero_indices(np_arr):
    # code here
    return

print("Test Case 1:")
np_arr_nine = np.array([10, 5, 0, 0, 50, 67, 99, 102, 0, 66666, 0])
print("Output:", find_zero_indices(np_arr_nine))
print("Expected Output: [2 3 8 10]")

<h1> Graphs and Visualization Questions </h1>

#### Q11) Create a 2D plot using matplotlib that visualizes the intersection of two parametric curves represented by the following equations
a) Equation 1

    x = cos(t)

    y = sin(t) * cos(t)

b) Equation 2

    x = 3 * cos(u)

    y = 3 * sin(u) * cos(u)

where t and u are parameters that vary between 0 and 2π

The graph should have the following properties:
1. The x and y axes should be labelled.
2. The graph should have a title.
3. The graph should have a legend.
4. Both the curve should have different colors.
5. Both the curve should have different line styles.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Generate parameter values
t = np.linspace(0, 2 * np.pi, 1000)
u = np.linspace(0, 2 * np.pi, 1000)

# Compute x and y values for the first curve


# Compute x and y values for the second curve


# Create the plot